name: TownySpawnUI
description: This plugin adds a browsable menu to teleport to other towns in Towny
author: Senkoco
main: me.senkoco.townyspawnui.Main
version: 1.1.0
api-version: 1.19
depend: [Towny]
permissions:
  townyspawnui.menu.open:
    description: Permission allowing you to open the menu
  townyspawnui.menu.teleport:
    description: Permission allowing you to teleport to other towns