name: TownySpawnUI
description: This plugin adds a browsable menu to teleport to other towns in Towny
author: Senkoco
main: me.senkoco.townyspawnui.Main
version: 1.2.0
api-version: 1.19
depend: [Towny]
permissions:
  townyspawnui.menu.open:
    description: Permission allowing you to open the menu
  townyspawnui.menu.teleport:
    description: Permission allowing you to teleport to other towns
  townyspawnui.set.town.item:
    description: Permission allowing town mayors to set their town's item in the menu
  townyspawnui.set.nation.item:
    description: Permission allowing nation kings to set their nation's item in the menu